# Generated by Django 4.2.3 on 2025-06-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='dependency_chain',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='running', max_length=20),
        ),
    ]
