# Generated by Django 4.2.3 on 2025-06-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_chain_dependency_chain_run_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='user_input_required',
            field=models.BooleanField(default=False),
        ),
    ]
