# Generated by Django 4.2.3 on 2025-06-25 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_agent_user_input_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='chain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='backend.chain'),
        ),
    ]
